### ISSUE TITLE
websockets daemon only listens on docker IP - thus does not work for web interface

### ISSUE THREAD

**Issue by sammcj** [dperson/pts#2]
The websockets server only listens on the docker IP, so it will never work when you try and connect to it remotely.

I'm not sure where in PTS you can set what IP it listens on, but it should be set to 0.0.0.0:someport

My [PR](https://github.com/dperson/pts/pull/1) will enable the web interface etc... but this will still be an issue.

**Comment by dperson** [comment]
IIRC, you have to specify 0.0.0.0:someport when it asks you for the port...
